spring:
  application:
    name: springBoot-mongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/app_db

server:
  port: 8081
  servlet:
    context-path: /api


#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
#      mongodb:
#        driver: DEBUG